---
title: "script"
author: "Stefan Fleck"
date: "12/1/2020"
output: html_document
---


## Intro

Hello, my name is Stefan and I work for the Transport Unit
at Statistics Austria. 

In 2019 we developed a mobile app for the road freight
transport survey as an alternative to the traditional questionnaire.

The app can automatically fill-in some of the data we need by analyzing the
geo-locations recorded by the mobile device, thus leaving fewer questions for
the respondent to answer and saving them valuable time. 

This talk is about how, and why, we implemented the processing of the location data
in R and set up a web service to make this functionality available to the
backend of the mobile app.

## TOC

1. I will start by discussing how we solved the problem of deriving travel distance from position data.

2. Next I will explain why we decided to choose a web-service for deploying our code 

3. And then, I will describe the actual service we implemented with the help of the plumber package

4. Finally, I will close the presentation with a conclusion and recommend
  some additional reading if you want to deepen your understanding of web
  services.

As this talk is rather short and aimed at people who have not used 
plumber before. I can only skim the topics listed above, but
I am happy to Answer questions afterwards.

 (1:20)
## 1.3

For the statistics we publish we need to know the total distance of each journey
and potentially all transitioned countries and border crossings. 

This can be derived from location data, but its not completely straight forward.

The mobile app records the global position of the device as latitude and 
longitude. 

Usually we get one such geo-position every few seconds, depending on
the device. 

As you can see on the maps, the data is not always perfect and
there are 
  - *outliers* that we have to *remove* and 
  - *gaps* that we have to *close*.
  
These *gaps* can be especially large for phones with *aggressive power saving* settings and
sometimes we only get a few points towards the beginning and end of a journey.


##

In the end we came up with the following algorithm for processing our data.

First we *remove points* where the positional accuracy reported by the
mobile phone is *less than 20 meters*. 

Then we *remove points* where the speed of the vehicle is 
*less than 7 kilometers per hour*. 

We do this to account for things like *rest breaks*, where the driver left his
vehicle but did not deactivate the app.

We also *remove points* where the speed is *greater than 130 kilometers per hour*.
This has proven very effective at removing *outliers*

We then *connect* the remaining points with *straight lines if they are close*
together, or use an *external routing service* to connect points that are *further than 50 meters apart.*

This algorithm produces *very good results* for most of the
journeys that we receive, however, our work does not stop with coming up with
the business logic for solving the problem. 

Now we have to think about how...

(3:20)
##

...we *deploy the solution* in a production environment? 

Note that *new journeys can arrive at any time* during the day and should 
be processed within a few minutes. 

Manually running an R script any time a new journey arrives is therefore not
feasible.

A better approach would be making an R script that is *callable from the command line* 
and deploying it to the machine where the *backend of the mobile app* runs.
The backend could then execute the script whenever it needed to process
a journey.

This has several disadvantages. 

First, It pushes the responsibility for maintaining the *R environment* to the 
team that developed the mobile app, rather than the developer of the R code.

It would also make the *setup of the backend* more *complicated* and therefore
add more potential failure points.

In addition, this also means that the app team would always need to be involved if the
*modifications* to the script become necessary. 

Alternatively, we could turn our R code into a *web service* and avoid most of 
these pitfalls!


## Advantages of using a web service

* By defining an API i can clearly formalize the boundaries between two components
  of system.
  
  This  often corrsepond to borders between teams, for example in our case
  where the IT unit maintains the mobile app and its backend, while we maintain the geoprocessing
  service.
* HTTP - the protocol over which we communicate with the web services - has been around for a long time, is well standardized and so practically
  all programming languages can use HTTP APIs.
  
*  Since the web service runs on a dedicated machine, I have total control over the
  the R execution environment, that means  the R version, operating system,
  R packages, system libraries, etc. 
  
* I can easily deploy different version of the service, for example a separate development,
  testing and production stage.
  
* The service is reusable from other projects. For example, I have also
  created a small shiny app that uses the same API to enable our staff to
  review the routes submitted with the mobile app.
  
  (6:20)


## Architecture 

Now lets look at the system from an architecture point of view. We have several
different pieces of software that need to communicate with each other.

* On the right you see the different components of our system.

* The mobile app needs to query and submit data from the backend. It
  does this via an HTTP API.

* On the bottom we have the routing service that we use to impute gaps in
  the location data. This one also uses an HTTP API

* So it is only logical that we also choose an HTTP API to expose
our R-based service.

* Each component of the system is self sufficient. We could reimplement
the geoprocessing service in a different programming lanague without
any downstream problems for mobile-app. 


## server code

Here is a code example for server side code with plumber.

We define a normal R function that we *augment* wit special comments that
are then turned into an API specification by plumber. 

This part here defines the so called *endpoint* of our api. 

The *id* gets passed to our R function as a *variable*. 

Plumber also passes a special *Response* object
named "res" into the function that we can manipulate. 

In this example we manipulate the object to return the *proper HTTP error*
codes if we encounter a problem. 

If you want to learn more about HTTP 
status codes, please refer to that link down here.


## client code

Accessing the api defined on the slide before is really easy. You can do it
from R or from the command line (with curl), or from practically any other programming
language. 

In R we can use the httr library to send HTTP requests. httr
is pretty smart and already parses the response for us if it comes in a format
that it can understand, like JSON or XML. 



## Api Documentation

* Usually an API has several endpoints. This is a partial overview of the
  endpoints our geoprocessing API provides. 
  
  Note that there are more types
  of requests, not just GET request that you can send over HTTP. For example,
  you can also send DELETE requests to indicate a resource should be deleted.
  
  If you implement an API it is very important to understand the semantics
  of different HTTP methods, and use them appropriately. Otherwise your
  API will be a mess and hard to use for other people. 
  
  Please refer to the link here for a detailed description of HTTP methods.
  
* Plumber automatically generates a documentation for your API. For this it
  turns special code comments into an OpenAPI compatible API specification.
  
* Sadly this is still not very feature-complete, and it is not yet possible to
  properly document important things like return values. This is for me one of 
  the major flaws in plumber, but If you really want you can manually write
  the OpenAPI specification in YAML or JSON and serve it via plumber.

## Conclusion

* HTTP APIs are a powerful tool to patch together different computer programs
* Providing services with well-behaved APIs is a great way for different teams 
  to colaborate in complex IT projects
* The plumber package makes it easy to create web services from R Projects, and
* the httr packages makes it very easy access HTTP APIs

To give you some motivation, in 2002 jeff bezos, the founder of amazon,
sent an infamous email to all his employees that teams are only allowed to expose 
their work to other teams through services with well defined APIs, and
that everyone who doesn comply gets fired. Now Amazon is the worlds most valuable company.


